"""The v2 contract, asserted against the COMPILED model rather than the source.

`robot_allcollisions_jaw.xml` is generated by `add_jaw.py` from an Onshape
export that gets regenerated periodically. The failure this file exists to
catch is silent: if a joint is inserted, renamed or reordered upstream, every
index in `tasks/v2.py` shifts, and the reward terms keep running — they just
address the wrong joints. That produced no error in v1, only months of
confusing runs, which is why the jaw went onto a new model in the first place.
"""

import mujoco
import pytest

from mjlab_microduck.robot.microduck_constants import MICRODUCK_JAW_XML
from mjlab_microduck.tasks.v2 import (
    JAW_JOINT_NAME,
    JAW_OPEN,
    LEG_JOINTS,
    NECK_JOINTS,
    V2_ACTION_DIM,
    V2_JOINT_NAMES,
    V2_OBS_DIM,
    joint_indices,
)


@pytest.fixture(scope="module")
def model():
    return mujoco.MjModel.from_xml_path(str(MICRODUCK_JAW_XML))


def _actuated_joint_names(model) -> list[str]:
    """Joint names in CTRL order — the order actions are applied in."""
    names = []
    for i in range(model.nu):
        jid = model.actuator_trnid[i, 0]
        names.append(mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_JOINT, jid))
    return names


def test_ctrl_order_matches_the_declared_v2_layout(model):
    assert _actuated_joint_names(model) == list(V2_JOINT_NAMES)


def test_action_dim_is_15(model):
    assert model.nu == V2_ACTION_DIM == 15


def test_obs_dim_follows_from_the_joint_count():
    # 3 ang_vel + 3 gravity + 3x15 joint state + 13 command block.
    assert 3 + 3 + 3 * V2_ACTION_DIM + 13 == V2_OBS_DIM == 64


def test_jaw_is_not_named_passive(model):
    # Every actuator/obs/reward selector in the repo matches `^(?!passive_).*`,
    # so a `passive_jaw` would be invisible to all of them.
    assert not JAW_JOINT_NAME.startswith("passive_")
    assert JAW_JOINT_NAME in V2_JOINT_NAMES


def test_jaw_sits_between_the_head_and_the_right_leg(model):
    # This is the whole reason v2 is a separate model: on v1 the right leg
    # starts at index 9, and six cfgs hardcode that literal.
    (jaw,) = joint_indices(JAW_JOINT_NAME)
    assert jaw == 9
    assert joint_indices("head_roll") == [8]
    assert joint_indices("right_hip_yaw") == [10]


def test_leg_and_neck_index_sets_are_disjoint_and_exclude_the_jaw():
    (jaw,) = joint_indices(JAW_JOINT_NAME)
    assert jaw not in LEG_JOINTS
    assert jaw not in NECK_JOINTS
    assert set(LEG_JOINTS) & set(NECK_JOINTS) == set()
    assert len(LEG_JOINTS) == 10
    assert len(NECK_JOINTS) == 4


def test_jaw_range_covers_the_declared_travel(model):
    joint_id = mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_JOINT, JAW_JOINT_NAME)
    assert joint_id >= 0
    lo, hi = model.jnt_range[joint_id]
    assert hi >= JAW_OPEN, f"jaw cannot open to {JAW_OPEN}: range is ({lo}, {hi})"
    # Closing must be able to go slightly past zero so the position servo keeps
    # loading an object that is already gripped rather than backing off it.
    assert lo <= 0.0


def test_beak_geoms_are_named_so_the_contact_sensor_can_address_them(model):
    names = {
        mujoco.mj_id2name(model, mujoco.mjtObj.mjOBJ_GEOM, i)
        for i in range(model.ngeom)
    }
    assert "jaw_collision" in names
    assert "upper_mouth_collision" in names


def test_jaw_tip_site_exists(model):
    # The approach-shaping reward measures beak-to-object distance from here.
    assert mujoco.mj_name2id(model, mujoco.mjtObj.mjOBJ_SITE, "jaw_tip") >= 0


def test_joint_indices_raises_on_an_unknown_joint():
    # The point of the helper: a renamed joint fails loudly instead of
    # silently re-pointing a reward at whatever now sits at that index.
    with pytest.raises(KeyError):
        joint_indices("left_elbow")


def test_v1_model_is_untouched():
    from mjlab_microduck.robot.microduck_constants import MICRODUCK_ALLCOLLISIONS_XML

    v1 = mujoco.MjModel.from_xml_path(str(MICRODUCK_ALLCOLLISIONS_XML))
    assert v1.nu == 14, "adding the jaw must not have changed the v1 model"
    assert JAW_JOINT_NAME not in _actuated_joint_names(v1)
